"""unique_venta

Revision ID: d8f1ce55d328
Revises: 56653d8fc003
Create Date: 2026-05-06 21:24:20.595321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f1ce55d328'
down_revision: Union[str, None] = '56653d8fc003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_venta_unica', 'ventas', ['fecha', 'cliente_id', 'producto_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_venta_unica', 'ventas', type_='unique')
    # ### end Alembic commands ###
