"""add analytics tables

Revision ID: 6cc2593259b7
Revises: 3c23b5c577e6
Create Date: 2026-05-08 02:37:32.010971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc2593259b7'
down_revision: Union[str, None] = '3c23b5c577e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('proveedor_id', sa.String(), nullable=False),
    sa.Column('proveedor_nombre', sa.String(), nullable=False),
    sa.Column('producto_id', sa.String(), nullable=False),
    sa.Column('producto_nombre', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha', 'proveedor_id', 'producto_id', name='idx_compra_unica')
    )
    op.create_index(op.f('ix_compras_id'), 'compras', ['id'], unique=False)
    op.create_table('cuentas_corrientes_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.Column('cliente_nombre', sa.String(), nullable=False),
    sa.Column('comprobante_id', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('saldo_acumulado', sa.Float(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comprobante_id', 'tipo', name='idx_cta_cte_cliente_unica')
    )
    op.create_index(op.f('ix_cuentas_corrientes_clientes_id'), 'cuentas_corrientes_clientes', ['id'], unique=False)
    op.create_table('cuentas_corrientes_proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.String(), nullable=False),
    sa.Column('proveedor_nombre', sa.String(), nullable=False),
    sa.Column('comprobante_id', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('saldo_acumulado', sa.Float(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comprobante_id', 'tipo', name='idx_cta_cte_proveedor_unica')
    )
    op.create_index(op.f('ix_cuentas_corrientes_proveedores_id'), 'cuentas_corrientes_proveedores', ['id'], unique=False)
    op.create_table('movimientos_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('saldo_acumulado', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha', 'tipo', 'descripcion', 'importe', name='idx_movimiento_caja_unico')
    )
    op.create_index(op.f('ix_movimientos_caja_id'), 'movimientos_caja', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_caja_id'), table_name='movimientos_caja')
    op.drop_table('movimientos_caja')
    op.drop_index(op.f('ix_cuentas_corrientes_proveedores_id'), table_name='cuentas_corrientes_proveedores')
    op.drop_table('cuentas_corrientes_proveedores')
    op.drop_index(op.f('ix_cuentas_corrientes_clientes_id'), table_name='cuentas_corrientes_clientes')
    op.drop_table('cuentas_corrientes_clientes')
    op.drop_index(op.f('ix_compras_id'), table_name='compras')
    op.drop_table('compras')
    # ### end Alembic commands ###
