"""add created_at to ventas

Revision ID: 3c23b5c577e6
Revises: d8f1ce55d328
Create Date: 2026-05-06 21:52:29.058907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c23b5c577e6'
down_revision: Union[str, None] = 'd8f1ce55d328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.add_column('ventas', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'created_at')
    pass
    # ### end Alembic commands ###
